
stages:
  - test
  - deploy

test/python35:
  stage: test
  image: python:3.5
  script:
    - pip install tox
    - tox -e py35

test/python36:
  stage: test
  image: python:3.6
  script:
    - pip install tox
    - tox -e py36

test/python37:
  stage: test
  image: python:3.7
  script:
    - pip install tox
    - tox -e py37

test/python38:
  stage: test
  image: python:3.8
  script:
    - pip install tox
    - tox -e py38

pages:
  stage: deploy
  image: python:3.7
  script:
  - pip install sphinx sphinx-argparse sphinx_rtd_theme
  - sphinx-build docs/ docs/_build/html
  - mv docs/_build/html public
  artifacts:
    paths:
    - public
  only:
  - master

pypi:
  stage: deploy
  image: python:3.7
  rules:
  - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/
    when: on_success
  script:
  - pip install twine
  - python setup.py sdist bdist_wheel
  - python -m twine upload dist/*
